apiVersion: v1
kind: Pod
metadata:
  namespace: demo-ns
  name: demo-pod
spec:
  containers:
  - image: nginx:alpine-slim
    name: demo-container
  affinity:
    podAnitAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: k2
            operator: In
            values:
            - v2
        topologyKey: "kubernetes.io/hostname"