apiVersion: v1
kind: Pod
metadata:
  namespace: demo-ns
  name: demo-pod
spec:
  containers:
  - name: demo-container
    image: nginx:alpine-slim
    resources:
      requests:
        cpu: 1
      limits:
        cpu: 2
